# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/jiang/soft/cmake-3.31.3/build/bin/cmake

# The command to remove a file.
RM = /home/jiang/soft/cmake-3.31.3/build/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jiang/helprop2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jiang/helprop2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/home/jiang/soft/cmake-3.31.3/build/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/home/jiang/soft/cmake-3.31.3/build/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jiang/helprop2/CMakeFiles /home/jiang/helprop2//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jiang/helprop2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named helprop

# Build rule for target.
helprop: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 helprop
.PHONY : helprop

# fast build rule for target.
helprop/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helprop.dir/build.make CMakeFiles/helprop.dir/build
.PHONY : helprop/fast

#=============================================================================
# Target rules for targets named HelProp

# Build rule for target.
HelProp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 HelProp
.PHONY : HelProp

# fast build rule for target.
HelProp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HelProp.dir/build.make CMakeFiles/HelProp.dir/build
.PHONY : HelProp/fast

#=============================================================================
# Target rules for targets named IOTest

# Build rule for target.
IOTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 IOTest
.PHONY : IOTest

# fast build rule for target.
IOTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IOTest.dir/build.make CMakeFiles/IOTest.dir/build
.PHONY : IOTest/fast

#=============================================================================
# Target rules for targets named ParticleTest

# Build rule for target.
ParticleTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ParticleTest
.PHONY : ParticleTest

# fast build rule for target.
ParticleTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParticleTest.dir/build.make CMakeFiles/ParticleTest.dir/build
.PHONY : ParticleTest/fast

#=============================================================================
# Target rules for targets named docopt

# Build rule for target.
docopt: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 docopt
.PHONY : docopt

# fast build rule for target.
docopt/fast:
	$(MAKE) $(MAKESILENT) -f docopt/CMakeFiles/docopt.dir/build.make docopt/CMakeFiles/docopt.dir/build
.PHONY : docopt/fast

src/HelProp.o: src/HelProp.cc.o
.PHONY : src/HelProp.o

# target to build an object file
src/HelProp.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HelProp.dir/build.make CMakeFiles/HelProp.dir/src/HelProp.cc.o
.PHONY : src/HelProp.cc.o

src/HelProp.i: src/HelProp.cc.i
.PHONY : src/HelProp.i

# target to preprocess a source file
src/HelProp.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HelProp.dir/build.make CMakeFiles/HelProp.dir/src/HelProp.cc.i
.PHONY : src/HelProp.cc.i

src/HelProp.s: src/HelProp.cc.s
.PHONY : src/HelProp.s

# target to generate assembly for a file
src/HelProp.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HelProp.dir/build.make CMakeFiles/HelProp.dir/src/HelProp.cc.s
.PHONY : src/HelProp.cc.s

src/IO.o: src/IO.cc.o
.PHONY : src/IO.o

# target to build an object file
src/IO.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helprop.dir/build.make CMakeFiles/helprop.dir/src/IO.cc.o
.PHONY : src/IO.cc.o

src/IO.i: src/IO.cc.i
.PHONY : src/IO.i

# target to preprocess a source file
src/IO.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helprop.dir/build.make CMakeFiles/helprop.dir/src/IO.cc.i
.PHONY : src/IO.cc.i

src/IO.s: src/IO.cc.s
.PHONY : src/IO.s

# target to generate assembly for a file
src/IO.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helprop.dir/build.make CMakeFiles/helprop.dir/src/IO.cc.s
.PHONY : src/IO.cc.s

src/IOTest.o: src/IOTest.cc.o
.PHONY : src/IOTest.o

# target to build an object file
src/IOTest.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IOTest.dir/build.make CMakeFiles/IOTest.dir/src/IOTest.cc.o
.PHONY : src/IOTest.cc.o

src/IOTest.i: src/IOTest.cc.i
.PHONY : src/IOTest.i

# target to preprocess a source file
src/IOTest.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IOTest.dir/build.make CMakeFiles/IOTest.dir/src/IOTest.cc.i
.PHONY : src/IOTest.cc.i

src/IOTest.s: src/IOTest.cc.s
.PHONY : src/IOTest.s

# target to generate assembly for a file
src/IOTest.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IOTest.dir/build.make CMakeFiles/IOTest.dir/src/IOTest.cc.s
.PHONY : src/IOTest.cc.s

src/ParticleTest.o: src/ParticleTest.cc.o
.PHONY : src/ParticleTest.o

# target to build an object file
src/ParticleTest.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParticleTest.dir/build.make CMakeFiles/ParticleTest.dir/src/ParticleTest.cc.o
.PHONY : src/ParticleTest.cc.o

src/ParticleTest.i: src/ParticleTest.cc.i
.PHONY : src/ParticleTest.i

# target to preprocess a source file
src/ParticleTest.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParticleTest.dir/build.make CMakeFiles/ParticleTest.dir/src/ParticleTest.cc.i
.PHONY : src/ParticleTest.cc.i

src/ParticleTest.s: src/ParticleTest.cc.s
.PHONY : src/ParticleTest.s

# target to generate assembly for a file
src/ParticleTest.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParticleTest.dir/build.make CMakeFiles/ParticleTest.dir/src/ParticleTest.cc.s
.PHONY : src/ParticleTest.cc.s

src/fcache.o: src/fcache.cc.o
.PHONY : src/fcache.o

# target to build an object file
src/fcache.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helprop.dir/build.make CMakeFiles/helprop.dir/src/fcache.cc.o
.PHONY : src/fcache.cc.o

src/fcache.i: src/fcache.cc.i
.PHONY : src/fcache.i

# target to preprocess a source file
src/fcache.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helprop.dir/build.make CMakeFiles/helprop.dir/src/fcache.cc.i
.PHONY : src/fcache.cc.i

src/fcache.s: src/fcache.cc.s
.PHONY : src/fcache.s

# target to generate assembly for a file
src/fcache.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helprop.dir/build.make CMakeFiles/helprop.dir/src/fcache.cc.s
.PHONY : src/fcache.cc.s

src/newton_solver.o: src/newton_solver.cc.o
.PHONY : src/newton_solver.o

# target to build an object file
src/newton_solver.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helprop.dir/build.make CMakeFiles/helprop.dir/src/newton_solver.cc.o
.PHONY : src/newton_solver.cc.o

src/newton_solver.i: src/newton_solver.cc.i
.PHONY : src/newton_solver.i

# target to preprocess a source file
src/newton_solver.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helprop.dir/build.make CMakeFiles/helprop.dir/src/newton_solver.cc.i
.PHONY : src/newton_solver.cc.i

src/newton_solver.s: src/newton_solver.cc.s
.PHONY : src/newton_solver.s

# target to generate assembly for a file
src/newton_solver.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helprop.dir/build.make CMakeFiles/helprop.dir/src/newton_solver.cc.s
.PHONY : src/newton_solver.cc.s

src/particle.o: src/particle.cc.o
.PHONY : src/particle.o

# target to build an object file
src/particle.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helprop.dir/build.make CMakeFiles/helprop.dir/src/particle.cc.o
.PHONY : src/particle.cc.o

src/particle.i: src/particle.cc.i
.PHONY : src/particle.i

# target to preprocess a source file
src/particle.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helprop.dir/build.make CMakeFiles/helprop.dir/src/particle.cc.i
.PHONY : src/particle.cc.i

src/particle.s: src/particle.cc.s
.PHONY : src/particle.s

# target to generate assembly for a file
src/particle.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helprop.dir/build.make CMakeFiles/helprop.dir/src/particle.cc.s
.PHONY : src/particle.cc.s

src/root_finding.o: src/root_finding.cc.o
.PHONY : src/root_finding.o

# target to build an object file
src/root_finding.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helprop.dir/build.make CMakeFiles/helprop.dir/src/root_finding.cc.o
.PHONY : src/root_finding.cc.o

src/root_finding.i: src/root_finding.cc.i
.PHONY : src/root_finding.i

# target to preprocess a source file
src/root_finding.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helprop.dir/build.make CMakeFiles/helprop.dir/src/root_finding.cc.i
.PHONY : src/root_finding.cc.i

src/root_finding.s: src/root_finding.cc.s
.PHONY : src/root_finding.s

# target to generate assembly for a file
src/root_finding.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helprop.dir/build.make CMakeFiles/helprop.dir/src/root_finding.cc.s
.PHONY : src/root_finding.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... HelProp"
	@echo "... IOTest"
	@echo "... ParticleTest"
	@echo "... docopt"
	@echo "... helprop"
	@echo "... src/HelProp.o"
	@echo "... src/HelProp.i"
	@echo "... src/HelProp.s"
	@echo "... src/IO.o"
	@echo "... src/IO.i"
	@echo "... src/IO.s"
	@echo "... src/IOTest.o"
	@echo "... src/IOTest.i"
	@echo "... src/IOTest.s"
	@echo "... src/ParticleTest.o"
	@echo "... src/ParticleTest.i"
	@echo "... src/ParticleTest.s"
	@echo "... src/fcache.o"
	@echo "... src/fcache.i"
	@echo "... src/fcache.s"
	@echo "... src/newton_solver.o"
	@echo "... src/newton_solver.i"
	@echo "... src/newton_solver.s"
	@echo "... src/particle.o"
	@echo "... src/particle.i"
	@echo "... src/particle.s"
	@echo "... src/root_finding.o"
	@echo "... src/root_finding.i"
	@echo "... src/root_finding.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

